### ISSUE TITLE
On Terminate crashing

### ISSUE THREAD

**Issue by raviteja786143** [jinatonic/confetti#6]
'void android.view.ViewParent.requestLayout()' on a null object reference
 
In your sample app ShimmeringActivity added on more button stop and on click listener 
getConfettiManager.terminate() crashing.

My use case will be I have to show infinite shower animation but on click on something dismiss the animation. Using terminate leads to crash copy pasting error log

` java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestLayout()' on a null object reference
                                                                                        at com.github.jinatonic.confetti.ConfettiView.terminate(ConfettiView.java:86)
                                                                                        at com.github.jinatonic.confetti.ConfettiManager.terminate(ConfettiManager.java:481)
                                                                                        at com.github.jinatonic.confetti.ConfettiManager$2.onAnimationUpdate(ConfettiManager.java:534)
                                                                                        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
                                                                                        at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1384)
                                                                                        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1427)
                                                                                        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:759)
                                                                                        at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:152)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5497)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by jinatonic** [comment]
Hi @raviteja786143 

I just updated the sample project to support termination, and I cannot reproduce your crash. Can you checkout the latest changes and verify your crash?
